
[cursor]
style = "Block"

[env]
TERM = "alacritty"

[font]
size = 18

[font.bold]
family = "Inconsolata Nerd Font"
style = "Regular"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Regular"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[window]
decorations = "full"
opacity = 0.9

[window.padding]
x = 15
y = 15

[colors.primary]
background = "#000000"
